const dummyDataDays = {
    days: [
        {
            datetime: "2024-11-01",
            datetimeEpoch: 1730419200,
            tempmax: 59.3,
            tempmin: 48.1,
            temp: 53,
            feelslikemax: 59.3,
            feelslikemin: 46.8,
            feelslike: 52.7,
            dew: 47.8,
            humidity: 83,
            precip: 0,
            precipprob: 0,
            precipcover: 0,
            preciptype: null,
            snow: 0,
            snowdepth: 0,
            windgust: 15.4,
            windspeed: 5.4,
            winddir: 315.8,
            pressure: 1025.8,
            cloudcover: 18.3,
            visibility: 15,
            solarradiation: 87.9,
            solarenergy: 7.4,
            uvindex: 4,
            severerisk: 10,
            sunrise: "06:54:47",
            sunriseEpoch: 1730444087,
            sunset: "16:32:41",
            sunsetEpoch: 1730478761,
            moonphase: 0,
            conditions: "Clear",
            description: "Clear conditions throughout the day.",
            icon: "clear-day",
            stations: null,
            source: "fcst",
        },
        {
            datetime: "2024-11-02",
            datetimeEpoch: 1730505600,
            tempmax: 58.7,
            tempmin: 50.4,
            temp: 53.8,
            feelslikemax: 58.7,
            feelslikemin: 50.4,
            feelslike: 53.8,
            dew: 47.4,
            humidity: 79.4,
            precip: 0.004,
            precipprob: 0,
            precipcover: 4.17,
            preciptype: ["rain"],
            snow: 0,
            snowdepth: 0,
            windgust: 21.3,
            windspeed: 9.2,
            winddir: 68.3,
            pressure: 1031.4,
            cloudcover: 80.1,
            visibility: 15,
            solarradiation: 49.6,
            solarenergy: 4.3,
            uvindex: 3,
            severerisk: 10,
            sunrise: "06:56:33",
            sunriseEpoch: 1730530593,
            sunset: "16:30:54",
            sunsetEpoch: 1730565054,
            moonphase: 0.03,
            conditions: "Partially cloudy",
            description: "Partly cloudy throughout the day.",
            icon: "partly-cloudy-day",
            stations: null,
            source: "fcst",
        },
        {
            datetime: "2024-11-03",
            datetimeEpoch: 1730592000,
            tempmax: 57.5,
            tempmin: 47.4,
            temp: 51.3,
            feelslikemax: 57.5,
            feelslikemin: 45.4,
            feelslike: 50.5,
            dew: 42.9,
            humidity: 73.7,
            precip: 0,
            precipprob: 0,
            precipcover: 0,
            preciptype: null,
            snow: 0,
            snowdepth: 0,
            windgust: 17.7,
            windspeed: 7.8,
            winddir: 71.1,
            pressure: 1029.3,
            cloudcover: 12.2,
            visibility: 15,
            solarradiation: 86.8,
            solarenergy: 7.4,
            uvindex: 4,
            severerisk: 10,
            sunrise: "06:58:19",
            sunriseEpoch: 1730617099,
            sunset: "16:29:08",
            sunsetEpoch: 1730651348,
            moonphase: 0.07,
            conditions: "Clear",
            description: "Clear conditions throughout the day.",
            icon: "clear-day",
            stations: null,
            source: "fcst",
        },
        {
            datetime: "2024-11-04",
            datetimeEpoch: 1730678400,
            tempmax: 57.6,
            tempmin: 46.3,
            temp: 50.8,
            feelslikemax: 57.6,
            feelslikemin: 44.6,
            feelslike: 50.1,
            dew: 39.2,
            humidity: 65.2,
            precip: 0,
            precipprob: 0,
            precipcover: 0,
            preciptype: null,
            snow: 0,
            snowdepth: 0,
            windgust: 16.1,
            windspeed: 5.8,
            winddir: 94,
            pressure: 1026.6,
            cloudcover: 1.7,
            visibility: 15,
            solarradiation: 85.8,
            solarenergy: 7.4,
            uvindex: 4,
            severerisk: 10,
            sunrise: "07:00:05",
            sunriseEpoch: 1730703605,
            sunset: "16:27:25",
            sunsetEpoch: 1730737645,
            moonphase: 0.1,
            conditions: "Clear",
            description: "Clear conditions throughout the day.",
            icon: "clear-day",
            stations: null,
            source: "fcst",
        },
        {
            datetime: "2024-11-05",
            datetimeEpoch: 1730764800,
            tempmax: 56.7,
            tempmin: 47.2,
            temp: 51.5,
            feelslikemax: 56.7,
            feelslikemin: 47.2,
            feelslike: 51.5,
            dew: 38.8,
            humidity: 62.3,
            precip: 0,
            precipprob: 0,
            precipcover: 0,
            preciptype: null,
            snow: 0,
            snowdepth: 0,
            windgust: 1.8,
            windspeed: 1.8,
            winddir: 84,
            pressure: 1026,
            cloudcover: 58.8,
            visibility: 15,
            solarradiation: 75.8,
            solarenergy: 6.6,
            uvindex: 3,
            severerisk: 10,
            sunrise: "07:01:51",
            sunriseEpoch: 1730790111,
            sunset: "16:25:43",
            sunsetEpoch: 1730823943,
            moonphase: 0.14,
            conditions: "Partially cloudy",
            description: "Partly cloudy throughout the day.",
            icon: "partly-cloudy-day",
            stations: null,
            source: "fcst",
        },
        {
            datetime: "2024-11-06",
            datetimeEpoch: 1730851200,
            tempmax: 58.4,
            tempmin: 48.5,
            temp: 53,
            feelslikemax: 58.4,
            feelslikemin: 48.5,
            feelslike: 53,
            dew: 42.8,
            humidity: 68.8,
            precip: 0,
            precipprob: 3.2,
            precipcover: 0,
            preciptype: null,
            snow: 0,
            snowdepth: 0,
            windgust: 4,
            windspeed: 2.7,
            winddir: 239.2,
            pressure: 1029.9,
            cloudcover: 54.8,
            visibility: 15,
            solarradiation: 75.4,
            solarenergy: 6.6,
            uvindex: 3,
            severerisk: 10,
            sunrise: "07:03:37",
            sunriseEpoch: 1730876617,
            sunset: "16:24:03",
            sunsetEpoch: 1730910243,
            moonphase: 0.17,
            conditions: "Partially cloudy",
            description: "Becoming cloudy in the afternoon.",
            icon: "partly-cloudy-day",
            stations: null,
            source: "fcst",
        },
        {
            datetime: "2024-11-07",
            datetimeEpoch: 1730937600,
            tempmax: 58.9,
            tempmin: 49.9,
            temp: 53.5,
            feelslikemax: 58.9,
            feelslikemin: 49.9,
            feelslike: 53.5,
            dew: 45.9,
            humidity: 76.6,
            precip: 0,
            precipprob: 0,
            precipcover: 0,
            preciptype: null,
            snow: 0,
            snowdepth: 0,
            windgust: 9.8,
            windspeed: 4.3,
            winddir: 95.2,
            pressure: 1032.7,
            cloudcover: 50.3,
            visibility: 15,
            solarradiation: 74.4,
            solarenergy: 6.3,
            uvindex: 3,
            severerisk: 10,
            sunrise: "07:05:23",
            sunriseEpoch: 1730963123,
            sunset: "16:22:25",
            sunsetEpoch: 1730996545,
            moonphase: 0.21,
            conditions: "Partially cloudy",
            description: "Becoming cloudy in the afternoon.",
            icon: "partly-cloudy-day",
            stations: null,
            source: "fcst",
        },
        {
            datetime: "2024-11-08",
            datetimeEpoch: 1731024000,
            tempmax: 57.3,
            tempmin: 48.3,
            temp: 51.7,
            feelslikemax: 57.3,
            feelslikemin: 46.6,
            feelslike: 51.1,
            dew: 44.8,
            humidity: 77.5,
            precip: 0,
            precipprob: 0,
            precipcover: 0,
            preciptype: null,
            snow: 0,
            snowdepth: 0,
            windgust: 19.2,
            windspeed: 8.3,
            winddir: 77.9,
            pressure: 1028.5,
            cloudcover: 0.6,
            visibility: 15,
            solarradiation: 74.1,
            solarenergy: 6.3,
            uvindex: 3,
            severerisk: 10,
            sunrise: "07:07:09",
            sunriseEpoch: 1731049629,
            sunset: "16:20:48",
            sunsetEpoch: 1731082848,
            moonphase: 0.24,
            conditions: "Clear",
            description: "Clear conditions throughout the day.",
            icon: "clear-day",
            stations: null,
            source: "fcst",
        },
        {
            datetime: "2024-11-09",
            datetimeEpoch: 1731110400,
            tempmax: 55.3,
            tempmin: 46.1,
            temp: 50,
            feelslikemax: 55.3,
            feelslikemin: 45,
            feelslike: 49.8,
            dew: 44,
            humidity: 80.4,
            precip: 0,
            precipprob: 6.5,
            precipcover: 0,
            preciptype: null,
            snow: 0,
            snowdepth: 0,
            windgust: 8.1,
            windspeed: 3.8,
            winddir: 145.1,
            pressure: 1025.5,
            cloudcover: 0.2,
            visibility: 15,
            solarradiation: 71.6,
            solarenergy: 6.3,
            uvindex: 3,
            severerisk: 10,
            sunrise: "07:08:54",
            sunriseEpoch: 1731136134,
            sunset: "16:19:14",
            sunsetEpoch: 1731169154,
            moonphase: 0.25,
            conditions: "Clear",
            description: "Clear conditions throughout the day.",
            icon: "clear-day",
            stations: null,
            source: "fcst",
        },
        {
            datetime: "2024-11-10",
            datetimeEpoch: 1731196800,
            tempmax: 56.6,
            tempmin: 47.4,
            temp: 51.1,
            feelslikemax: 56.6,
            feelslikemin: 47.4,
            feelslike: 51.1,
            dew: 46.9,
            humidity: 86,
            precip: 0,
            precipprob: 9.7,
            precipcover: 0,
            preciptype: null,
            snow: 0,
            snowdepth: 0,
            windgust: 6.3,
            windspeed: 3.4,
            winddir: 253.2,
            pressure: 1029.3,
            cloudcover: 42.2,
            visibility: 15,
            solarradiation: 63.8,
            solarenergy: 5.7,
            uvindex: 2,
            severerisk: 10,
            sunrise: "07:10:39",
            sunriseEpoch: 1731222639,
            sunset: "16:17:41",
            sunsetEpoch: 1731255461,
            moonphase: 0.31,
            conditions: "Partially cloudy",
            description: "Partly cloudy throughout the day.",
            icon: "partly-cloudy-day",
            stations: null,
            source: "fcst",
        },
        {
            datetime: "2024-11-11",
            datetimeEpoch: 1731283200,
            tempmax: 56.9,
            tempmin: 48.6,
            temp: 52.1,
            feelslikemax: 56.9,
            feelslikemin: 48.6,
            feelslike: 52.1,
            dew: 42.1,
            humidity: 69.1,
            precip: 0,
            precipprob: 12.9,
            precipcover: 0,
            preciptype: null,
            snow: 0,
            snowdepth: 0,
            windgust: 2.2,
            windspeed: 2.2,
            winddir: 212.2,
            pressure: 1032,
            cloudcover: 32.3,
            visibility: 15,
            solarradiation: 67.9,
            solarenergy: 5.7,
            uvindex: 3,
            severerisk: 10,
            sunrise: "07:12:24",
            sunriseEpoch: 1731309144,
            sunset: "16:16:11",
            sunsetEpoch: 1731341771,
            moonphase: 0.35,
            conditions: "Partially cloudy",
            description: "Partly cloudy throughout the day.",
            icon: "partly-cloudy-day",
            stations: null,
            source: "fcst",
        },
        {
            datetime: "2024-11-12",
            datetimeEpoch: 1731369600,
            tempmax: 55.8,
            tempmin: 47.9,
            temp: 51.1,
            feelslikemax: 55.8,
            feelslikemin: 47.9,
            feelslike: 51.1,
            dew: 44.4,
            humidity: 78.2,
            precip: 0,
            precipprob: 16.1,
            precipcover: 0,
            preciptype: null,
            snow: 0,
            snowdepth: 0,
            windgust: 2.7,
            windspeed: 2.7,
            winddir: 104.6,
            pressure: 1029,
            cloudcover: 5.1,
            visibility: 15,
            solarradiation: 66.5,
            solarenergy: 5.4,
            uvindex: 3,
            severerisk: 10,
            sunrise: "07:14:09",
            sunriseEpoch: 1731395649,
            sunset: "16:14:43",
            sunsetEpoch: 1731428083,
            moonphase: 0.38,
            conditions: "Clear",
            description: "Clear conditions throughout the day.",
            icon: "clear-day",
            stations: null,
            source: "fcst",
        },
        {
            datetime: "2024-11-13",
            datetimeEpoch: 1731456000,
            tempmax: 53.9,
            tempmin: 46.5,
            temp: 49.5,
            feelslikemax: 53.9,
            feelslikemin: 45.6,
            feelslike: 49.2,
            dew: 45.2,
            humidity: 85.7,
            precip: 0,
            precipprob: 19.4,
            precipcover: 0,
            preciptype: null,
            snow: 0,
            snowdepth: 0,
            windgust: 14.4,
            windspeed: 4.1,
            winddir: 312.7,
            pressure: 1029.4,
            cloudcover: 65.4,
            visibility: 15,
            solarradiation: 58.8,
            solarenergy: 5.1,
            uvindex: 2,
            severerisk: 10,
            sunrise: "07:15:53",
            sunriseEpoch: 1731482153,
            sunset: "16:13:17",
            sunsetEpoch: 1731514397,
            moonphase: 0.42,
            conditions: "Partially cloudy",
            description: "Partly cloudy throughout the day.",
            icon: "partly-cloudy-day",
            stations: null,
            source: "fcst",
        },
        {
            datetime: "2024-11-14",
            datetimeEpoch: 1731542400,
            tempmax: 51.3,
            tempmin: 45.6,
            temp: 49,
            feelslikemax: 51.3,
            feelslikemin: 42.6,
            feelslike: 48,
            dew: 41.3,
            humidity: 76,
            precip: 0,
            precipprob: 9.7,
            precipcover: 0,
            preciptype: null,
            snow: 0,
            snowdepth: 0,
            windgust: 15.2,
            windspeed: 7.4,
            winddir: 27.5,
            pressure: 1033.6,
            cloudcover: 94.7,
            visibility: 15,
            solarradiation: 25.8,
            solarenergy: 2.4,
            uvindex: 1,
            severerisk: 10,
            sunrise: "07:17:36",
            sunriseEpoch: 1731568656,
            sunset: "16:11:53",
            sunsetEpoch: 1731600713,
            moonphase: 0.45,
            conditions: "Overcast",
            description: "Cloudy skies throughout the day.",
            icon: "cloudy",
            stations: null,
            source: "fcst",
        },
    ],
};

const months = [
    { name: "January", numDays: 31 },
    { name: "Febuary", numDays: 28 },
    { name: "March", numDays: 31 },
    { name: "April", numDays: 30 },
    { name: "May", numDays: 31 },
    { name: "June", numDays: 31 },
    { name: "July", numDays: 30 },
    { name: "August", numDays: 31 },
    { name: "September", numDays: 30 },
    { name: "October", numDays: 31 },
    { name: "November", numDays: 30 },
    { name: "December", numDays: 31 },
];

const todos = [
    {
        "id": crypto.randomUUID(),
        "title": "Daily Standup",
        "type": "daily",
        "timeUnit": 1,
        "time": "09:00",
        "date": "2024-11-01"
    },
    {
        "id": crypto.randomUUID(),
        "title": "Weekly Report",
        "type": "weekly",
        "timeUnit": 2,
        "time": "10:00",
        "dayOfWeek": 1
    },
    {
        "id": crypto.randomUUID(),
        "title": "Monthly Review",
        "type": "monthly",
        "timeUnit": 1,
        "time": "15:00",
        "dayOfMonth": 1
    }
]

export { dummyDataDays, months, todos };